name: Python Lint

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.x

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.8.17'
          enable-cache: true

      - name: Install dependencies
        run: |
          cd packages/sdks/python
          uv venv
          uv sync --all-extras --all-groups

      - name: Lint code
        run: |
          cd packages/sdks/python
          uv run scripts/lint.py
